### ISSUE TITLE
Switch to Datmapper

### ISSUE THREAD

**Issue by tdgs** [ruby-diplomacy/rails-diplomacy#7]
Επειδή το ActiveRecord έχει αρχίσει και μου τη δίνει στα νεύρα, ψήνομαι να το αλλάξω για το [DataMapper](http://datamapper.org/)
Έκανα [ερώτηση στο StackOverflow](http://stackoverflow.com/questions/8527459/using-datamapper-with-existing-rails-application) και ήδη μου απάντησαν.

Να το δοκιμάσω σε ένα δικό μου branch και αν παίξει να το κάνω merge στο master;

**Comment by frontierpsycho** [comment]
Αχα, μια χαρά ακούγεται. Πρέπει να μάθω κι εγώ λίγο DM,

**Comment by tdgs** [comment]
Done in 19b293fc6a2433bc6745abf65e4b74e3f6008252 merged to master
